### ISSUE TITLE
incorrect data used for web percy report in generate.js

### ISSUE THREAD

**Issue by BhumikaBBrowserstack** [BrowserStackCE/percy-report#19]
## The problem

In generate.js file, below logic should be updated for web percy in else block:

else {
                let browser = getComparisonBrowser(comp)
                compTag = **device**.name
                if (!report.browsers.includes(browser.name)) {
                    report.browsers.push(browser.name)
                }
                if (!report.widths.includes(comparison['width'])) {
                    report.widths.push(comparison['width'])
                }

Here, device(highlighted in the above code) should be updated to **browser**
Because of this bug, when we try to generate report for a web percy build we get the below error:
`(node:32915) UnhandledPromiseRejectionWarning: ReferenceError: device is not defined
    at /Users/bhumikababbar/.nvm/versions/node/v14.16.0/lib/node_modules/percy-report/src/generate.js:94:17
    at Array.map (<anonymous>)
    at /Users/bhumikababbar/.nvm/versions/node/v14.16.0/lib/node_modules/percy-report/src/generate.js:79:85
    at Array.map (<anonymous>)
    at module.exports.Generate (/Users/bhumikababbar/.nvm/versions/node/v14.16.0/lib/node_modules/percy-report/src/generate.js:74:39)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.<anonymous> (/Users/bhumikababbar/.nvm/versions/node/v14.16.0/lib/node_modules/percy-report/bin/cli.js:21:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:32915) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:32915) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by princebaretto99** [comment]
Fixed in this PR: https://github.com/BrowserStackCE/percy-report/pull/18
